# Generated by Django 5.0.7 on 2024-08-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arizalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=200)),
                ('ism', models.CharField(max_length=200)),
                ('sharif', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
                ('pasport_serya', models.CharField(max_length=200)),
                ('pasport_raqam', models.CharField(max_length=200)),
                ('jshr', models.CharField(max_length=200)),
                ('pasport_rasm', models.FileField(upload_to='pasport_rasm/')),
                ('daraja', models.CharField(max_length=200)),
                ('yonalish', models.CharField(max_length=200)),
                ('diplom_serya_raqam', models.CharField(max_length=200)),
                ('diplom_rasm', models.FileField(upload_to='diplom_rasm/')),
                ('bitirgan_yil', models.CharField(max_length=200)),
                ('bitirgan_muassasa', models.CharField(max_length=400)),
                ('viloyat', models.CharField(max_length=200)),
                ('tuman', models.CharField(max_length=200)),
                ('kocha', models.CharField(max_length=200)),
                ('rozilik', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('rasm', models.FileField(upload_to='yangilik/')),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
