# Generated by Django 5.0.7 on 2024-08-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arizalar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizalar',
            name='natariyus_diplom',
            field=models.FileField(default=1, upload_to='diplom_rasm/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arizalar',
            name='natariyus_pasport',
            field=models.FileField(default=1, upload_to='pasport_rasm/'),
            preserve_default=False,
        ),
    ]
